use_frameworks!

target 'podTestLibary_Example' do
  pod 'podTestLibary', :path => '../'

  target 'podTestLibary_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
